<?php

namespace NC\FaqBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FaqElemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqElemRepository extends EntityRepository
{
}
